### ISSUE TITLE
help

### ISSUE THREAD

**Issue by NyxKazuya** [kleiton0x00/RedditC2#1]
I put user, password, subreddit, listenerID. I get this and it closes without connecting

https://i.imgur.com/txC7GEQ.png

**Comment by kleiton0x00** [comment]
Hi, when compiling the C# agent, it is required to installed the required Libraries: `RedditSharp`. Please follow the next steps:

1. Click on **Project** tab and click on **Manage NuGet Packages...**
![install_vs_library](https://user-images.githubusercontent.com/37262788/206898665-80dba22f-f380-4075-b950-4602e77548a9.jpg)

2. Click on **Browse** and search for **RedditSharp**. Install the version **1.1.13**:
![Screenshot from 2022-12-11 11-29-32](https://user-images.githubusercontent.com/37262788/206898734-d32d5f9e-56a3-4534-935e-4f10a521d433.png)

If the error happens again, please let me know.

**Comment by NyxKazuya** [comment]
> Hi, when compiling the C# agent, it is required to installed the required Libraries: `RedditSharp`. Please follow the next steps:
> 
> 1. Click on **Project** tab and click on **Manage NuGet Packages...**
>    ![install_vs_library](https://user-images.githubusercontent.com/37262788/206898665-80dba22f-f380-4075-b950-4602e77548a9.jpg)
> 2. Click on **Browse** and search for **RedditSharp**. Install the version **1.1.13**:
>    ![Screenshot from 2022-12-11 11-29-32](https://user-images.githubusercontent.com/37262788/206898734-d32d5f9e-56a3-4534-935e-4f10a521d433.png)
> 
> If the error happens again, please let me know.


prove on the same compiled PC works. but in another virtual with windows recently installed it gives me this.
https://i.imgur.com/o6HY2AL.png

**Comment by kleiton0x00** [comment]
I was able to reproduce and fix the issue: the dlls were separated from the compiled exe. I used **ILMerge** to solve this issue. I updated the whole repository so please feel try to clone it again.

Once compiled, the exe will be located in this directory: /bin/Release/ILMerge/RedditAgent.exe

If you still somehow get the same error, please take follow the steps of this article for the compilation: https://www.inogic.com/blog/2018/06/automate-ilmerge-for-workflowsplugins-to-merge-multiple-assemblies-into-one-in-dynamics-365/

**Comment by kleiton0x00** [comment]
Closing the issue due to inactivity.
