### ISSUE TITLE
Community banned

### ISSUE THREAD

**Issue by RingZero89** [kleiton0x00/RedditC2#2]
Hi! It works well but the community is banned quickly.

**Comment by kleiton0x00** [comment]
Hi, have you tried creating and using a private subreddit instead?

**Comment by RingZero89** [comment]
yes! Maybe, need to hide the traffic...

**Comment by kleiton0x00** [comment]
I've updated the C2 by adding an encrypted traffic and **stealth_mode** (look at the [wiki](https://github.com/kleiton0x00/RedditC2/wiki)) which clear the logs every time you receive the task result. Hopefully it resolves your issue.

**Comment by kleiton0x00** [comment]
Closing the issue due to inactivity.
